#!/bin/bash


# 自签证书生成
# 自签证书验证
# openssl x509 -in notarysignerserver.crt -text -noout


DOMAIN="notarysigner"
CERT_DIR="./"
COUNTRY="CN"
STATE="ZHEJIANG"
CITY="HANGZHOU"
ORG_NAME="DIY"
EMAIL="admin@gmail.com"
KEY_SIZE="2048"
DAYS="365"

# 方法一
# 1、生成ca根证书
## 创建私钥/生成加密私钥
openssl genrsa -out "$DOMAIN"rootCA.key $KEY_SIZE
#openssl genrsa -des3 -out rootCA.key 2048

## 根据请求生成ca根证书
openssl req -new -x509 -days 365 -key "$DOMAIN"rootCA.key -subj "/C=$COUNTRY/ST=$STATE/L=$CITY/O=$ORG_NAME/CN=$DOMAIN" -out "$DOMAIN"rootCA.crt
### 将"$DOMAIN"rootCA.crt证书导入到浏览器即可完成授信




# 2、生成CA自签证书
## 创建私钥key和crs
openssl req -newkey rsa:2048 -nodes -keyout "$DOMAIN"server.key -subj "/C=$COUNTRY/ST=$STATE/L=$CITY/O=$ORG_NAME/CN=$DOMAIN" -out "$DOMAIN"server.csr

## 使用CA根证书签名CRT
openssl x509 -req -extfile <(printf "subjectAltName=DNS:$DOMAIN,DNS:www.$DOMAIN") -days 365 -in "$DOMAIN"server.csr -CA "$DOMAIN"rootCA.crt -CAkey "$DOMAIN"rootCA.key -CAcreateserial -out "$DOMAIN"server.crt
### 生成ip证书
openssl x509 -req -extfile <(printf "subjectAltName=IP:$DOMAIN") -days 365 -in "$DOMAIN"server.csr -CA "$DOMAIN"rootCA.crt -CAkey "$DOMAIN"rootCA.key -CAcreateserial -out "$DOMAIN"server.crt

# 方法二
##或通过一条命令进行生成根证书
#openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes -keyout rootCA-key.pem -subj "/C=$COUNTRY/ST=$STATE/L=$CITY/O=$ORG_NAME/CN=$DOMAIN" -out rootCA.crt
## rootCA.crt证书导入到浏览器即可完成授信
## 生成证书文件
#openssl req -x509 -newkey rsa:2048 -sha256 -days 3650 -nodes -keyout "$DOMAIN"cert.pem -CA rootCA.crt -CAkey rootCA-key.pem  -subj "/C=$COUNTRY/ST=$STATE/L=$CITY/O=$ORG_NAME/CN=$DOMAIN" -addext "subjectAltName=IP:$DOMAIN" -out "$DOMAIN"cert.crt

## 检查证书
#openssl x509 -in 59.202.51.174server.crt -text -noout

# jdk授信
# cd $JAVA_HOME/jre/lib/security
# keytool -importcert -trustcacerts -keystore cacerts --storepass changeit -alias rootCA -file CA.crt -noprompt
# keytool -importcert -trustcacerts -keystore cacerts --storepass changeit -alias app -file private.crt -noprompt

# prometheus 客户端证书生成
# openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -keyout node_exporter.key -out node_exporter.crt -subj "/C=CN/ST=Beijing/L=Beijing/O=test.cn/CN=localhost"
